package com.mycompany.cajeroview;

import com.mycompany.cajeropersistencia.DAOS.ClientesDAO;
import com.mycompany.cajeropersistencia.DAOS.DomicilioDAO;
import com.mycompany.cajeropersistencia.DAOS.IClientesDAO;
import com.mycompany.cajeropersistencia.DAOS.IDomicilioDAO;
import com.mycompany.cajeropersistencia.DAOS.IUsuarioDAO;
import com.mycompany.cajeropersistencia.DAOS.UsuarioDAO;
import com.mycompany.cajeropersistencia.DTO.ClienteNuevoDTO;
import com.mycompany.cajeropersistencia.DTO.DomicilioNuevoDTO;
import com.mycompany.cajeropersistencia.DTO.UsuarioNuevoDTO;
import com.mycompany.cajeropersistencia.conexion.IConexion;
import com.mycompany.cajeropersistencia.exceptions.PersistenciaException;
import com.mycompany.cajeropersistencia.exceptions.ValidacionDTOException;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import com.mycompany.cajeroview.SignUpForm;


/**
 *
 * @author TeLesheo
 */
public class SignUpForm extends javax.swing.JFrame {

    /**
     * Creates new form ClienteForm
     */
    private IConexion conexionBD;
    private UsuarioNuevoDTO usuarioNuevo;

    public SignUpForm(IConexion conexionBD,UsuarioNuevoDTO usuarioNuevo) {

        initComponents();

        this.conexionBD = conexionBD;
        this.usuarioNuevo = usuarioNuevo;

    }

    public void registrarCliente() throws PersistenciaException {
        String nomrbe = txt_nombres.getText();
        String apellido_paterno = txt_apellido_paterno.getText();
        String apellido_materno = txt_apellido_materno.getText();
        String fecha_nacimiento = txt_fecha_nacimiento.getText();
        int codigo_postal = Integer.parseInt(txt_codigo_postal.getText());
        String calle = txt_calle.getText();
        int numero_interior = Integer.parseInt(txt_numero_interior.getText());
        int numero_exterior = Integer.parseInt(txt_numero_exterior.getText());

        ClienteNuevoDTO clienteNuevo = new ClienteNuevoDTO();
        DomicilioNuevoDTO domicilioNuevo = new DomicilioNuevoDTO();

        IClientesDAO clienteDAO = new ClientesDAO(conexionBD);
        IDomicilioDAO domicilioDAO = new DomicilioDAO(conexionBD);
        IUsuarioDAO usuarioDAO = new UsuarioDAO(conexionBD);

        clienteNuevo.setNombres(nomrbe);
        clienteNuevo.setApellido_paterno(apellido_paterno);
        clienteNuevo.setApellido_materno(apellido_materno);
        clienteNuevo.setFecha_nacimiento(fecha_nacimiento);

        domicilioNuevo.setCalle(calle);
        domicilioNuevo.setCodigo_postal(codigo_postal);
        domicilioNuevo.setNumero_exterior(numero_exterior);
        domicilioNuevo.setNumero_interior(numero_interior);

//        usuarioDAO.agregaUsuario(usuarioNuevo);
//        clienteDAO.agregar_cliente(clienteNuevo,usuarioNuevo);
//        domicilioDAO.agregar(domicilioNuevo);
//        

       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txt_nombres = new javax.swing.JTextField();
        btn_registrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_apellido_paterno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_apellido_materno = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_fecha_nacimiento = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_codigo_postal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_calle = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_numero_exterior = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_numero_interior = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(17, 31, 77));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(242, 244, 247));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_nombres.setBackground(new java.awt.Color(255, 255, 255));
        txt_nombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombresActionPerformed(evt);
            }
        });
        jPanel1.add(txt_nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 150, 30));

        btn_registrar.setBackground(new java.awt.Color(0, 194, 206));
        btn_registrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_registrar.setForeground(new java.awt.Color(242, 244, 247));
        btn_registrar.setText("Registrar");
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 125, 38));

        jLabel4.setFont(new java.awt.Font("Avenir Next Condensed", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Nombre(s)");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 48));

        jLabel5.setFont(new java.awt.Font("Avenir Next Condensed", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Apellido paterno");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, 48));

        txt_apellido_paterno.setBackground(new java.awt.Color(255, 255, 255));
        txt_apellido_paterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_apellido_paternoActionPerformed(evt);
            }
        });
        jPanel1.add(txt_apellido_paterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 150, 30));

        jLabel6.setFont(new java.awt.Font("Avenir Next Condensed", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Apellido Materno");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, 48));

        txt_apellido_materno.setBackground(new java.awt.Color(255, 255, 255));
        txt_apellido_materno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_apellido_maternoActionPerformed(evt);
            }
        });
        jPanel1.add(txt_apellido_materno, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 150, 30));

        jLabel7.setFont(new java.awt.Font("Avenir Next Condensed", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Información de dirección");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 48));

        txt_fecha_nacimiento.setBackground(new java.awt.Color(255, 255, 255));
        txt_fecha_nacimiento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jPanel1.add(txt_fecha_nacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 150, 30));

        jLabel8.setFont(new java.awt.Font("Avenir Next Condensed", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Fecha nacimiento");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 48));

        jLabel9.setFont(new java.awt.Font("Avenir Next Condensed", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Código postal");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, 48));

        txt_codigo_postal.setBackground(new java.awt.Color(255, 255, 255));
        txt_codigo_postal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codigo_postalActionPerformed(evt);
            }
        });
        jPanel1.add(txt_codigo_postal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 90, 30));

        jLabel10.setFont(new java.awt.Font("Avenir Next Condensed", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Calle");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, 48));

        txt_calle.setBackground(new java.awt.Color(255, 255, 255));
        txt_calle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_calleActionPerformed(evt);
            }
        });
        jPanel1.add(txt_calle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 250, 30));

        jLabel11.setFont(new java.awt.Font("Avenir Next Condensed", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Número exterior");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 110, 48));

        txt_numero_exterior.setBackground(new java.awt.Color(255, 255, 255));
        txt_numero_exterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_numero_exteriorActionPerformed(evt);
            }
        });
        jPanel1.add(txt_numero_exterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 110, 30));

        jLabel12.setFont(new java.awt.Font("Avenir Next Condensed", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Número interior");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, -1, 48));

        txt_numero_interior.setBackground(new java.awt.Color(255, 255, 255));
        txt_numero_interior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_numero_interiorActionPerformed(evt);
            }
        });
        jPanel1.add(txt_numero_interior, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 110, 30));

        jPanel2.add(jPanel1, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombresActionPerformed

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_registrarActionPerformed

    private void txt_apellido_paternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_apellido_paternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_apellido_paternoActionPerformed

    private void txt_apellido_maternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_apellido_maternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_apellido_maternoActionPerformed

    private void txt_codigo_postalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codigo_postalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigo_postalActionPerformed

    private void txt_calleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_calleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_calleActionPerformed

    private void txt_numero_exteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_numero_exteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_numero_exteriorActionPerformed

    private void txt_numero_interiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_numero_interiorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_numero_interiorActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SignUpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                SignUpForm dialog = new SignUpForm(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_registrar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_apellido_materno;
    private javax.swing.JTextField txt_apellido_paterno;
    private javax.swing.JTextField txt_calle;
    private javax.swing.JTextField txt_codigo_postal;
    private javax.swing.JFormattedTextField txt_fecha_nacimiento;
    private javax.swing.JTextField txt_nombres;
    private javax.swing.JTextField txt_numero_exterior;
    private javax.swing.JTextField txt_numero_interior;
    // End of variables declaration//GEN-END:variables
}
